
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: SumbalTariq2404
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ez_employee_tracking_development

test:
  <<: *default
  database: ez_employee_tracking_test
  
production:
  <<: *default
  database: ez_employee_tracking_production
  username: ez_employee_tracking
  password: <%= ENV['EZ_EMPLOYEE_TRACKING_DATABASE_PASSWORD'] %>
